'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{normalizeModel,exportDxf,auditDxf}=require('../packages/cad-export');
const root=path.resolve(__dirname,'..'),dist=path.join(root,'apps/engineering-web/dist'),fixturePath=path.join(root,'examples/r5-1-wow-cabinet/project.json'),catalogPath=path.join(root,'catalog/generated/catalog-assets.json'),port=Number(process.env.CNB_DEMO_PORT||8080); const fixture=JSON.parse(fs.readFileSync(fixturePath,'utf8')); let demo=JSON.parse(JSON.stringify(fixture));
const send=(res,status,data,type)=>{res.writeHead(status,{'Content-Type':type||'application/json; charset=utf-8','Cache-Control':'no-store'});if(Buffer.isBuffer(data)||typeof data==='string')res.end(data);else res.end(JSON.stringify(data));}; const readBody=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>resolve(s));req.on('error',reject);});
const rect=c=>({x:c.x,y:c.y,width:c.rotation%180?c.height:c.width,height:c.rotation%180?c.width:c.height});
function validate(){const p=demo.enclosure.mountingPlate,e=[],w=[];const a=demo.components.filter(c=>c.x>=0);for(let i=0;i<a.length;i++){const r=rect(a[i]);if(r.x<p.x||r.y<p.y||r.x+r.width>p.x+p.width||r.y+r.height>p.y+p.height)e.push({code:'E001',message:a[i].tag+' nằm ngoài plate'});for(let j=i+1;j<a.length;j++){const q=rect(a[j]);if(!(r.x+r.width<=q.x||q.x+q.width<=r.x||r.y+r.height<=q.y||q.y+q.height<=r.y))e.push({code:'E002',message:a[i].tag+' overlap '+a[j].tag});}}demo.components.filter(c=>c.assetId).forEach(c=>w.push({code:'V-CAD-CANDIDATE',message:c.tag+' là CAD candidate; chưa dùng làm footprint chế tạo'}));return{valid:e.length===0,errors:e,warnings:w};}
function layout(){const t=process.hrtime.bigint(),rails=demo.rails,groups={power:rails[0],control:rails[1],terminal:rails[2],auxiliary:rails[1]},cursor={};Object.keys(groups).forEach(k=>cursor[k]=groups[k].x);demo.components.forEach(c=>{if(c.locked&&c.x>=0)return;const r=groups[c.group]||rails[1];let x=cursor[c.group]||r.x;if(x+c.width>r.x+r.length)x=r.x;c.x=Math.round(x/5)*5;c.y=Math.round((r.y+r.height+8)/5)*5;c.railId=r.id;cursor[c.group]=x+c.width+10;});const v=validate(),area=demo.components.filter(c=>c.x>=0).reduce((s,c)=>s+c.width*c.height,0),p=demo.enclosure.mountingPlate;return{run_id:'run-'+Date.now().toString(36),duration_ms:Number((Number(process.hrtime.bigint()-t)/1e6).toFixed(3)),placements:demo.components.filter(c=>c.x>=0).map(c=>({device_id:c.id,x:c.x,y:c.y,locked:!!c.locked,rail_id:c.railId})),validation:v,metrics:{device_count:demo.components.length,placed_count:demo.components.filter(c=>c.x>=0).length,rail_count:rails.length,duct_count:demo.ducts.length,overlap_count:v.errors.filter(x=>x.code==='E002').length,space_utilization_percent:Number((100*area/(p.width*p.height)).toFixed(2)),warning_count:v.warnings.length}};}
function asset(id){const m=JSON.parse(fs.readFileSync(catalogPath,'utf8'));const r=m.records.find(x=>(x.source_asset_id||x.id)===id);if(!r)return null;const p=path.resolve(root,'catalog',r.relative_path||'');return fs.existsSync(p)?{record:r,data:fs.readFileSync(p)}:null;}
function exportBundle(){const model=normalizeModel({project:demo.project,enclosure:demo.enclosure,mountingPlate:demo.enclosure.mountingPlate,rails:demo.rails,ducts:demo.ducts,components:demo.components,connections:demo.connections,metadata:demo.metadata}),dxf=exportDxf(model),audit=auditDxf(dxf),rows=['tag,description,manufacturer,order_code,status'];demo.components.forEach(c=>rows.push([c.tag,c.name,c.manufacturer,c.partNumber,c.status].map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(',')));return{artifact_id:'artifact-'+Date.now().toString(36),generated_at:new Date().toISOString(),project:demo.project,artifacts:{layout_dxf:{filename:'CNB-Demo-Cabinet.dxf',content:dxf,bytes:Buffer.byteLength(dxf)},bom_csv:{filename:'CNB-Demo-Cabinet-BOM.csv',content:rows.join('\n')+'\n',bytes:Buffer.byteLength(rows.join('\n'))}},audit:{valid:audit.valid,entityCount:audit.entityCount,sections:audit.sections}};}
function staticFile(req,res){let u=new URL(req.url,'http://localhost').pathname;if(u==='/demo'||u==='/demo/')u='/demo.html';const candidates=[path.resolve(dist,'.'+u),path.resolve(root,'apps/engineering-web',u.replace(/^\//,'')),path.resolve(root,'apps/engineering-web/public',u.replace(/^\//,''))];const p=candidates.find(x=>fs.existsSync(x)&&fs.statSync(x).isFile());if(!p)return send(res,404,'Not found','text/plain');const ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};return send(res,200,fs.readFileSync(p),types[ext]||'application/octet-stream');}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return send(res,200,{ok:true,service:'cnb-engineering-demo'});if(u.pathname==='/api/demo/project')return send(res,200,demo);if(u.pathname==='/api/demo/reset'&&req.method==='POST'){demo=JSON.parse(JSON.stringify(fixture));return send(res,200,{ok:true,project:demo});}if((u.pathname==='/api/demo/auto-layout'||u.pathname==='/api/demo/re-layout')&&req.method==='POST')return send(res,200,layout());if(u.pathname==='/api/demo/lock'&&req.method==='POST'){const p=JSON.parse(await readBody(req)),c=demo.components.find(x=>x.id===p.device_id);if(!c)return send(res,404,{error:'device not found'});c.locked=!!p.locked;return send(res,200,{ok:true,locked:c.locked});}const cm=u.pathname.match(/^\/api\/demo\/cad\/([A-Za-z0-9-]+)$/);if(cm){const a=asset(cm[1]);if(!a)return send(res,404,{error:'CAD asset not found'});return send(res,200,a.data,'application/dxf');}if(u.pathname==='/api/demo/export'&&req.method==='POST')return send(res,200,exportBundle());return staticFile(req,res);}catch(e){return send(res,500,{error:e.message});}});
server.listen(port,'127.0.0.1',()=>console.log('CNB Engineering Demo ready:\nhttp://127.0.0.1:'+port+'/demo'));
