'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const net = require('node:net');
const path = require('node:path');
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const root = path.resolve(__dirname, '..');

function reservePort() { return new Promise((resolve) => { const s = net.createServer(); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => resolve(p)); }); }); }
async function ready(url, child) { for (let i = 0; i < 60; i += 1) { if (child.exitCode !== null) throw new Error('server exited'); try { if ((await fetch(`${url}/api/health`)).ok) return; } catch (_) {} await new Promise((r) => setTimeout(r, 100)); } throw new Error('server timeout'); }
const approx = (a, b, tolerance = 2) => Math.abs(a - b) <= tolerance;

(async () => {
  const port = await reservePort(); const base = `http://127.0.0.1:${port}`; const child = spawn(process.execPath, [path.join(root, 'apps/web/server.js'), String(port)], { cwd: root, windowsHide: true, stdio: 'ignore' }); const browser = await chromium.launch({ headless: true });
  try {
    await ready(base, child); const page = await browser.newPage({ viewport: { width: 1440, height: 900 } }); await page.goto(base, { waitUntil: 'networkidle' }); await page.waitForFunction(() => window.CNB_APP.state.assetCatalog.length === 58);
    const manifest = await page.evaluate(() => ({ assets: window.CNB_APP.state.assetCatalog, products: window.CNB_APP.state.assetCatalog.map((a) => a.product_id) })); assert.equal(manifest.assets.length, 58); const etPair = await page.evaluate(() => { const records = window.CNB_APP.state.assetCatalog.filter((a) => /et200sp-1515sp-pc-cpu/.test(a.candidate_product_key || '')); return { count: records.length, views: records.map((a) => a.candidate_view).sort(), products: [...new Set(records.map((a) => a.product_id))] }; }); assert.deepEqual(etPair.views, ['front', 'side']); assert.equal(etPair.products.length, 1);
    const unknown = await page.evaluate(() => window.CNB_APP.state.assetCatalog.find((a) => a.source_group === 'radica-dxf' && a.unit_confidence === 'unknown' && a.preview_segment_count > 0 && !a.physical_footprint_id)); assert.ok(unknown); assert.equal(unknown.physical_width_mm, null); assert.equal(unknown.physical_height_mm, null); assert.equal(unknown.unit_confidence, 'unknown');

    await page.locator('#assetTab').click(); const card = page.locator(`.asset-card[data-asset-id="${unknown.id}"]`); await card.click(); await page.screenshot({ path: path.join(root, 'evidence', 'screenshots', '08-unit-review-library.png'), fullPage: true }); await page.locator('#addPreviewAsset').click(); const previewState = await page.evaluate(() => ({ component: window.CNB_APP.state.model.components.at(-1), issues: window.CNB_APP.state.issues.map((i) => i.code) })); assert.equal(previewState.component.width, 75); assert.ok(previewState.issues.includes('E012')); await page.locator('#autoLayout').click(); assert.equal(await page.evaluate((id) => window.CNB_APP.state.model.components.find((c) => c.id === id).x, previewState.component.id), previewState.component.x); await page.evaluate(() => window.CNB_APP.exportFormat('dxf')); assert.match(await page.locator('#toast').textContent(), /Export blocked/); await page.screenshot({ path: path.join(root, 'evidence', 'screenshots', '09-preview-only-asset.png'), fullPage: true });

    await card.click(); await page.locator('#assetReviewForm select[name="unit"]').selectOption('mm'); await page.locator('#assetReviewForm select[name="view"]').selectOption('front'); await page.locator('#assetReviewForm input[name="width"]').fill('23.8125'); await page.locator('#assetReviewForm input[name="height"]').fill('95.25'); await page.locator('#assetReviewForm button[type="submit"]').click(); await page.waitForFunction((id) => window.CNB_APP.state.assetCatalog.find((a) => a.id === id).review_state === 'approved-footprint', unknown.id); const approved = await page.evaluate((id) => window.CNB_APP.state.assetCatalog.find((a) => a.id === id), unknown.id); assert.equal(approved.unit_confidence, 'confirmed-by-review'); assert.equal(approved.physical_width_mm, 23.8125); await page.locator('#addPreviewAsset').click(); const approvedState = await page.evaluate(() => ({ component: window.CNB_APP.state.model.components.at(-1), issues: window.CNB_APP.state.issues.map((i) => i.code) })); assert.equal(approvedState.component.width, 23.8125); assert.equal(approvedState.component.height, 95.25); assert.ok(!approvedState.issues.includes('E012')); const imageBounds = await page.evaluate((id) => { const c = window.CNB_APP.state.model.components.find((x) => x.id === id); const image = document.querySelector(`[data-component-id="${id}"] image`); return { component: { width: c.width, height: c.height }, rendered: { width: Number(image.getAttribute('width')), height: Number(image.getAttribute('height')) } }; }, approvedState.component.id); assert.ok(approx(imageBounds.component.width, imageBounds.rendered.width, .001)); assert.ok(approx(imageBounds.component.height, imageBounds.rendered.height, .001)); await page.screenshot({ path: path.join(root, 'evidence', 'screenshots', '10-approved-real-footprint.png'), fullPage: true });

    const customModels = await page.evaluate(() => [
      ['small', 600, 900], ['tall', 800, 2000], ['wide', 2000, 800],
    ].map(([name, width, height]) => { const model = window.CNB_APP.scenarios.starter(); model.project.name = name; model.enclosure.width = width; model.enclosure.height = height; model.mountingPlate.width = width - 100; model.mountingPlate.height = height - 100; return model; }));
    const fits = []; for (const model of customModels) { await page.evaluate((m) => window.CNB_APP.loadModel(m, m.project.name), model); await page.evaluate(() => window.CNB_APP.fitCanvas()); fits.push(await page.evaluate(() => { const v = document.querySelector('#canvasViewport').getBoundingClientRect(); const s = document.querySelector('#panelSvg').getBoundingClientRect(); return { zoom: window.CNB_APP.state.zoom, fits: s.width <= v.width && s.height <= v.height, ratio: s.width / s.height }; })); } assert.ok(fits.every((fit) => fit.fits && fit.zoom >= .1 && fit.zoom <= 20));

    await page.evaluate(() => { window.CNB_APP.loadModel(window.CNB_APP.scenarios.starter(), 'coordinate test'); const c = window.CNB_APP.state.model.components[0]; c.x = 100; c.y = 200; window.CNB_APP.fitCanvas(); window.CNB_APP.zoomAt({ clientX: 700, clientY: 420 }, 5); window.CNB_APP.state.panX = 73; window.CNB_APP.state.panY = -41; window.CNB_APP.render(); });
    const coord = await page.evaluate(() => { const c = window.CNB_APP.state.model.components[0]; const svg = document.querySelector(`[data-component-id="${c.id}"]`); const b = svg.getBoundingClientRect(); return { id: c.id, x: c.x, y: c.y, sx: b.left + b.width / 2, sy: b.top + b.height / 2 }; }); const beforeCoord = { x: coord.x, y: coord.y }; await page.mouse.move(coord.sx, coord.sy); await page.mouse.down(); await page.mouse.move(coord.sx + 50, coord.sy + 25); await page.mouse.up(); const afterCoord = await page.evaluate((id) => { const c = window.CNB_APP.state.model.components.find((x) => x.id === id); return { x: c.x, y: c.y, selected: window.CNB_APP.state.selectedId }; }, coord.id); assert.equal(afterCoord.x % 5, 0); assert.equal(afterCoord.y % 5, 0); assert.notDeepEqual(afterCoord, beforeCoord, JSON.stringify({ coord, beforeCoord, afterCoord })); await page.screenshot({ path: path.join(root, 'evidence', 'screenshots', '11-zoom-500-percent.png'), fullPage: true });

    const emptyViewport = page.locator('#canvasViewport'); const eb = await emptyViewport.boundingBox(); const panEmpty = async (button) => { const before = await page.evaluate(() => ({ x: window.CNB_APP.state.panX, y: window.CNB_APP.state.panY })); await page.mouse.move(eb.x + eb.width - 14, eb.y + 14); await page.mouse.down({ button }); await page.mouse.move(eb.x + eb.width - 74, eb.y + 64); await page.mouse.up({ button }); const after = await page.evaluate(() => ({ x: window.CNB_APP.state.panX, y: window.CNB_APP.state.panY })); return { before, after }; }; const rightPan = await panEmpty('right'); const middlePan = await panEmpty('middle'); assert.ok(rightPan.after.x !== rightPan.before.x || rightPan.after.y !== rightPan.before.y); assert.ok(middlePan.after.x !== middlePan.before.x || middlePan.after.y !== middlePan.before.y); await page.screenshot({ path: path.join(root, 'evidence', 'screenshots', '12-pan-empty-viewport.png'), fullPage: true });
    await page.evaluate(() => window.CNB_APP.zoomAt({ clientX: 700, clientY: 420 }, .001)); assert.equal(await page.evaluate(() => window.CNB_APP.state.zoom), .1); await page.evaluate(() => window.CNB_APP.zoomAt({ clientX: 700, clientY: 420 }, 100)); assert.equal(await page.evaluate(() => window.CNB_APP.state.zoom), 20);
    const report = { ok: true, catalog_parse_58_of_58: true, unknown_units_not_assumed_mm: true, physical_dimension_clamp_removed: true, front_side_grouping_correct: true, approval_gating_correct: true, rendered_bounds_match_physical_bounds: true, cursor_zoom_stationary: true, right_pan_empty_viewport: true, middle_pan_empty_viewport: true, drag_after_zoom_pan_mm_correct: true, snap_after_zoom_pan: true, fit_geometry_correct: true, zoom_min: .1, zoom_max: 20, fit_ratios: fits }; fs.writeFileSync(path.join(root, 'evidence', 'test-logs', 'cad-hardening.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
  } finally { await browser.close(); child.kill(); }
})().catch((error) => { console.error(error.stack || error.message); process.exitCode = 1; });
