'use strict';

const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const net = require('node:net');

function reservePort() { return new Promise((resolve, reject) => { const s = net.createServer(); s.once('error', reject); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => resolve(p)); }); }); }
async function wait(base) { for (let i = 0; i < 50; i += 1) { try { if ((await fetch(`${base}/api/health`)).ok) return; } catch (_) {} await new Promise((r) => setTimeout(r, 100)); } throw new Error('server did not start'); }

(async () => {
  const port = await reservePort(); const base = `http://127.0.0.1:${port}`; const child = spawn(process.execPath, [path.join(__dirname, '..', 'apps', 'web', 'server.js'), String(port)], { cwd: path.join(__dirname, '..'), windowsHide: true, stdio: 'ignore' });
  try {
    await wait(base);
    const products = await (await fetch(`${base}/api/r3/products`)).json(); assert.equal(products.products.length, 8);
    const c6 = products.products.find((product) => product.type_designation === 'S201U-C6'); const c16 = products.products.find((product) => product.type_designation === 'S201U-C16'); const c63 = products.products.find((product) => product.type_designation === 'S201U-C63');
    assert.equal(c6.manufacturer_order_code, '2CDS271417R0064'); assert.equal(c16.manufacturer_order_code, '2CDS271417R0164'); assert.equal(c63.manufacturer_order_code, '2CDS271417R0634');
    assert.equal(c16.provenance.vendor_mounting_position.status, 'document_verified'); assert.equal(c16.provenance.allowed_rotations.status, 'engineering_default'); assert.equal(c16.provenance.service_access_direction.status, 'unknown');
    const eir = await (await fetch(`${base}/api/benchmark/r3`)).json(); assert.equal(eir.metadata.authoritative, true);
    const valid = await fetch(`${base}/api/export`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: eir, format: 'audit' }) }); assert.equal(valid.status, 200);
    const invalid = JSON.parse(JSON.stringify(eir)); invalid.placements[0].x = 0;
    const blocked = await fetch(`${base}/api/export`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: invalid, format: 'dxf' }) }); assert.equal(blocked.status, 422); const blockedBody = await blocked.json(); assert.ok(blockedBody.validation.errors.some((issue) => issue.code === 'E001'));
    const accessBlockedModel = { metadata: { authoritative: true }, enclosure: { width: 300, height: 300, depth: 200 }, mountingPlate: { x: 20, y: 20, width: 260, height: 260 }, rails: [], ducts: [], components: [{ id: 'a', tag: 'A', name: 'Access source', partNumber: 'A-1', x: 50, y: 100, width: 40, height: 40, mounting: 'Plate', terminals: [{ id: 'T1' }], metadata: { serviceAccessDirection: 'right', serviceAccessDepthMm: 100, clearanceMm: 0, widthProvenance: { status: 'document_verified' }, heightProvenance: { status: 'document_verified' }, depthProvenance: { status: 'document_verified' }, mountingProvenance: { status: 'document_verified' }, clearanceStatus: 'engineering_default', terminalModelStatus: 'document_verified' } }, { id: 'b', tag: 'B', name: 'Blocking source', partNumber: 'B-1', x: 80, y: 100, width: 40, height: 40, mounting: 'Plate', terminals: [], metadata: { clearanceMm: 0, widthProvenance: { status: 'document_verified' }, heightProvenance: { status: 'document_verified' }, depthProvenance: { status: 'document_verified' }, mountingProvenance: { status: 'document_verified' }, clearanceStatus: 'engineering_default', terminalModelStatus: 'unknown' } }] }; const accessBlocked = await fetch(`${base}/api/export`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: accessBlockedModel, format: 'dxf' }) }); assert.equal(accessBlocked.status, 422); const accessBody = await accessBlocked.json(); const accessMessages = JSON.stringify(accessBody.validation.errors); assert.ok(accessMessages.includes('access') || accessMessages.includes('service'));
    const missingProvenance = JSON.parse(JSON.stringify(eir)); missingProvenance.parts[0].provenance.width_mm = { status: 'unknown' }; const missing = await fetch(`${base}/api/export`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: missingProvenance, format: 'dxf' }) }); assert.equal(missing.status, 422); const missingBody = await missing.json(); assert.ok(missingBody.validation.errors.some((issue) => issue.code === 'E010'));
    const deviceId = eir.placements[0].device_id; const saved = await fetch(`${base}/api/eir/revisions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ eir, command: { type: 'lock', device_id: deviceId, locked: true } }) }); assert.equal(saved.status, 200); const revision = await saved.json(); assert.equal(revision.eir.placements.find((item) => item.device_id === deviceId).locked, true); const reloaded = await (await fetch(`${base}/api/eir/revisions/${revision.revision}`)).json(); assert.equal(reloaded.canonical_hash, revision.canonical_hash);
    const report = { ok: true, productCount: products.products.length, verifiedTypeOrderChecks: ['S201U-C6', 'S201U-C16', 'S201U-C63'], validExportStatus: valid.status, invalidExportStatus: blocked.status, blockedCodes: blockedBody.validation.errors.map((issue) => issue.code), accessBlockedStatus: accessBlocked.status, missingProvenanceStatus: missing.status, roundTripRevision: revision.revision, lockedDevice: deviceId };
    fs.mkdirSync(path.join(__dirname, '..', 'evidence', 'test-logs'), { recursive: true }); fs.writeFileSync(path.join(__dirname, '..', 'evidence', 'test-logs', 'r3-api.json'), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
  } finally { child.kill(); }
})().catch((error) => { console.error(error.stack || error.message); process.exitCode = 1; });
