const { chromium } = require('playwright');
const base = process.env.CNB_R4_URL || 'http://127.0.0.1:4177';
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  console.log('goto');
  await page.goto(base, { waitUntil: 'domcontentloaded' });
  console.log('loaded');
  await page.waitForTimeout(800);
  await page.selectOption('#scenarioSelect', 'r4');
  console.log('selected');
  await page.click('#loadScenario');
  console.log('scenario loaded');
  await page.waitForTimeout(300);
  await page.click('#assetTab');
  await page.selectOption('#assetFilter', 'units');
  console.log('asset tab');
  await page.screenshot({ path: 'evidence/r4/01-real-dxf-library.png', fullPage: true });
  const cards = page.locator('#assetList .asset-card');
  const cardCount = await cards.count();
  if (cardCount < 5) throw new Error(`expected catalog cards, got ${cardCount}`);
  const unknownAssetId = await page.evaluate(() => window.CNB_APP.state.assetCatalog.find((asset) => !(asset.unit_confidence === 'confirmed-from-dxf' && asset.units === 'millimetres'))?.source_asset_id);
  const beforeRejectedDrop = await page.evaluate(() => window.CNB_APP.state.model.components.length);
  await page.evaluate((id) => {
    const transfer = new DataTransfer();
    transfer.setData('text/cnb-asset', id);
    const target = document.querySelector('#panelSvg');
    target.dispatchEvent(new DragEvent('dragover', { bubbles: true, dataTransfer: transfer }));
    target.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: transfer, clientX: 620, clientY: 430 }));
  }, unknownAssetId);
  const afterRejectedDrop = await page.evaluate(() => window.CNB_APP.state.model.components.length);
  if (unknownAssetId && afterRejectedDrop !== beforeRejectedDrop) throw new Error('unknown-unit asset was accepted into known-unit scenario');
  const first = cards.first();
  const assetId = await first.getAttribute('data-asset-id');
  console.log('asset', assetId);
  await page.evaluate((id) => {
    const transfer = new DataTransfer();
    transfer.setData('text/cnb-asset', id);
    const target = document.querySelector('#panelSvg');
    target.dispatchEvent(new DragEvent('dragover', { bubbles: true, dataTransfer: transfer }));
    target.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: transfer, clientX: 620, clientY: 430 }));
  }, assetId);
  console.log('drop dispatched');
  const stateAfterDrop = await page.evaluate(() => ({ components: window.CNB_APP.state.model.components.length, firstAsset: window.CNB_APP.state.model.components.at(-1)?.assetId }));
  if (!stateAfterDrop.firstAsset || stateAfterDrop.components < 6) throw new Error(`asset drop did not create semantic component: ${JSON.stringify(stateAfterDrop)}`);
  await page.screenshot({ path: 'evidence/r4/02-placed-real-dxf.png', fullPage: true });
  await page.evaluate(() => { window.CNB_APP.state.zoom = 5; window.CNB_APP.render(); });
  await page.screenshot({ path: 'evidence/r4/03-deep-zoom-500-percent.png', fullPage: false });
  await page.evaluate(() => { window.CNB_APP.state.zoom = 1; window.CNB_APP.fitCanvas(); });
  await page.evaluate(() => { window.CNB_APP.state.selectedId = 'r4-component-1'; window.CNB_APP.render(); });
  await page.click('#toggleLock');
  const before = await page.evaluate(() => { const c = window.CNB_APP.state.model.components.find((item) => item.id === 'r4-component-1'); return { x: c.x, y: c.y, locked: c.locked }; });
  await page.click('#autoLayout');
  const after = await page.evaluate(() => { const c = window.CNB_APP.state.model.components.find((item) => item.id === 'r4-component-1'); return { x: c.x, y: c.y, locked: c.locked, images: document.querySelectorAll('#panelSvg image').length }; });
  if (!before.locked || before.x !== after.x || before.y !== after.y || after.images < 5) throw new Error(`lock/real render failed: ${JSON.stringify({ before, after })}`);
  await page.screenshot({ path: 'evidence/r4/04-lock-regenerate.png', fullPage: true });
  await first.click();
  await page.screenshot({ path: 'evidence/r4/05-asset-detail-three-statuses.png', fullPage: true });
  await browser.close();
  console.log(JSON.stringify({ ok: true, cardCount, stateAfterDrop, before, after }, null, 2));
})().catch((error) => { console.error(error.stack || error); process.exitCode = 1; });
